### ISSUE TITLE
SDK is resolved from an unpinned sibling checkout, so no commit records which SDK it was built against

### ISSUE THREAD

**Issue by ergofobe** [ergofobe/imogen-server#16]
## The problem

`package.json` resolves the client packages out of a checkout that lives outside this repository:

```json
"overrides": {
  "@imogen/shared": "file:../imogen-sdk/typescript/packages/shared",
  "@imogen/sdk": "file:../imogen-sdk/typescript/packages/sdk"
}
```

Nothing in this repository records **which** `imogen-sdk` commit a given commit here was built and
tested against. `imogen-ios` and `imogen-android` do record it — they pin the SDK as a git
submodule, so their history says exactly what they built against. This repo and `imogen-cli` do not.

## Why it matters

**CI is unpinned.** `.github/workflows/ci.yml` checks the SDK out with no `ref:`, so every run
builds against whatever `imogen-sdk`'s default branch happens to be at that moment:

```yaml
- uses: actions/checkout@v5
  with:
    repository: ergofobe/imogen-sdk
    path: imogen-sdk
```

A commit that was green can go red with no change to this repository, and re-running CI on an old
commit does not reproduce what that commit was originally tested against. `git bisect` across an
SDK-sensitive failure is not meaningful.

**A fresh clone at a tag does not rebuild that tag.** v0.2.0 checked out today builds against
today's SDK, not the SDK it shipped with.

**Local working state leaks into the build.** The build takes whatever is in the sibling working
tree — including a feature branch or uncommitted edits. There is no runtime API version
negotiation to catch a mismatch, so a stale or diverged sibling fails silently rather than loudly.
Bun copies `file:` dependencies rather than symlinking them, which adds a second staleness layer on
top: an SDK edit does not reach this repo until `bun install --force`.

**The layout constraint leaks into everything that builds.** Because the path escapes the
repository root, the Docker build has to take the parent directory as its context:

```yaml
# The context holds both repositories: the client packages come from the
# sibling checkout, and a build context cannot reach outside itself.
context: .
file: imogen-server/Dockerfile
```

The same constraint is load-bearing for local git worktrees: a worktree not named `imogen-server`
with an `imogen-sdk` beside it resolves the SDK to the wrong place, or to nothing.

## Options

Reporting the problem only — not proposing to do the work in this issue.

1. **Make `imogen-sdk` a git submodule**, as `imogen-ios` and `imogen-android` already do. The
   submodule pointer records the exact SDK commit, `actions/checkout` with `submodules: true` pins
   CI automatically, the override becomes `file:./imogen-sdk/typescript/...`, and both the
   Docker-context and worktree-layout constraints go away. The cost is the usual submodule
   ergonomics: `--recurse-submodules` on clone, and `git worktree add` does not populate submodules.

2. **Publish `@imogen/sdk` and `@imogen/shared` to npm** and delete the `overrides` block — what
   CONTRIBUTING.md already anticipates ("Deleting it is the whole of the change once the packages
   are on npm"). Strictly the better end state, but more work, and it means versioning the contract
   while it is still moving.

These are not exclusive; (1) is a reasonable interim for (2). Worth deciding alongside the same
problem in `imogen-cli`, since the two repos should not drift to different answers.

**Comment by ergofobe** [comment]
The same problem in the Rust CLI: ergofobe/imogen-cli#7. Both repos resolve the SDK as an unpinned sibling; `imogen-ios` and `imogen-android` pin it as a submodule. Worth one decision across both.

**Comment by ergofobe** [comment]
Upstream root fix filed as ergofobe/imogen-sdk#3 — publishing the packages is option 2 here. Note the TypeScript port has no build step today (`"build": "echo no build step"`, entry points aimed at `src/index.ts`), so npm publishing is further off than the metadata suggests.

**Comment by ergofobe** [comment]
Implemented in #20 (option 1: submodule).

Verified before merge:

- `bun run verify` — 708 pass / 0 fail across 38 files, identical to the pre-change
  baseline on `main`; 176 files linted, also identical
- `docker build -t imogen .` with the new repo-root context — succeeds end to end
  through the runtime stage
- Both runs done with the sibling `imogen-sdk` worktree **deleted**, so resolution
  could not silently fall back to it
- CI green on the branch: `check` 1m39s, `docker` 2m11s

Two things this turned up that the issue did not anticipate:

- `file:./imogen-sdk/...` — the form sketched above — makes bun normalise the override
  and the SDK's own nested `@imogen/shared` dependency to two different store keys,
  installing two copies of the Zod schemas. The override is spelled `file:imogen-sdk/...`
  without the `./` for that reason, and CONTRIBUTING.md now says so.
- Nesting the SDK put its tooling in our path: biome found the SDK's root `biome.json`
  nested under ours and refused to run at all, and a bare `bun test` ran the SDK's own
  four test files as if they were ours. Both are excluded now.

Also worth recording: while this was in flight, ergofobe/imogen-sdk#5 merged as `ac2c610`
and turned `main` red here — `bun run typecheck` against it fails with
`TS2307: Cannot find module '@imogen/shared'`, because it repoints `main`/`types`/`exports`
at `./dist`. That is exactly the failure this issue predicted, and pinning to `9e6a17a`
fixed it. The next submodule bump is therefore a breaking one; see the notes in #20.
